name: Enforcing pylint checks
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
    tags:
      - v*

jobs:
  update_python:
    runs-on: ubuntu-latest
    name: Running pylint checks
    steps:
      - name: Install Python 3.7
        run: sudo apt-get install -y --no-install-recommends python3.7 python3-pip && sudo ln -sfn /usr/bin/python3.7 /usr/bin/python3
        id: install_python_3_7
      - name: Update pip
        run: python3 -m pip install --upgrade --no-cache-dir pip
        id: pip-install
      - name: Fetch/update setuptools
        run: python3 -m pip install --upgrade --no-cache-dir setuptools
        id: setuptools-install
      - name: Fetch/update pylint
        run: python3 -m pip install --upgrade --no-cache-dir pylint
        id: pylint-install
      - name: Fetch source code
        uses: actions/checkout@v2
        id: fetch-source
      - name: Finding files
        run: find . -type f -name "*.py" > action_pylint_files.txt
        id: find-python-files
      - name: Clear out old installations
        run: 'python3 -m pip uninstall -y numpy && sudo apt remove -y python3-numpy'
        id: clean-old
      - name: Install system requirements
        shell: bash
        run: 'sudo apt-get update && sudo apt-get install -y python3-gdal gdal-bin libgdal-dev gcc g++ python3.7-dev'
        id: install-system-reqs
      - name: Install Python requirements
        shell: bash
        run: 'sudo python3 -m pip install --no-cache-dir wheel && sudo python3 -m pip install --no-cache-dir numpy pygdal==2.2.3.5'
        id: install-python-reqs
      - name: Run action pylint script
        shell: bash
        run: '[ -s "action_pylint.sh" ] && (chmod +x "action_pylint.sh" && ./action_pylint.sh) || (echo "Not running special action script - empty or not found")'
        id: run-special-action-script
      - name: Fetching pylint.rc file
        run: wget https://raw.githubusercontent.com/AgPipeline/Organization-info/master/pylint.rc
        id: fetch_pylint_resource
      - name: Listing
        run: ls -la
      - name: Files to be linted
        run: cat action_pylint_files.txt
      - name: Running pylint
        run: cat action_pylint_files.txt | xargs python3 -m pylint --rcfile ./pylint.rc
